### ISSUE TITLE
MouseMiddleButton() and TranslationKey() not reacting

### ISSUE THREAD

**Issue by stephanschulz** [roymacdonald/ofxCameraSaveLoad#3]
Hi

Thanks for the addon.
It loads the ofxEasyCamera perspective very well.
But middle and right mouse button interaction stops working when using your addon.
I check in the saved and loaded file and there variables seemed to be save to enable those features.

Would you know why it's not working?

Thanks a bunch.

```
bEnableMouseMiddleButton
1
bMouseInputEnabled
1
drag
0.9
doTranslationKey
m

```

**Comment by stephanschulz** [comment]
solved it i hope.
had to add cam.setAutoDistance(true); in setup()

**Comment by roymacdonald** [comment]
hey @stephanschulz that fix sounds a bit odd. I'll go through it and check what is going on.
best

**Comment by roymacdonald** [comment]
Hey @stephanschulz  I just updated the whole thing, can you please check if this issue still persists?
cheers

**Comment by stephanschulz** [comment]
i am on OS X 10.10.5 with OF 0.9.8
i am getting a lot of ofEasyCam error with your need addon

<img width="1537" alt="screen shot 2017-04-13 at 9 32 03 am" src="https://cloud.githubusercontent.com/assets/1054816/25006764/27fa0896-202c-11e7-807e-57466eb6b5f5.png">

**Comment by roymacdonald** [comment]
Hi, I see. I updated it for v0.10. I will fix that right now.
thanks for letting me know.

**Comment by roymacdonald** [comment]
Hey @stephanschulz Just fixed it. Now it works correctly in both v0.9.8 and v0.10
Let me know if it works for you.
best

**Comment by stephanschulz** [comment]
Hey @roymacdonald thanks for looking in to this.
It does compile. 

Saving works for the pose but not for the location of the cube. When i drag it to the button left for example, hit save, drag it somewhere else, hit load, it will be placed in the middle of the screen.

thx

**Comment by roymacdonald** [comment]
hey @stephanschulz  fixed once again.

**Comment by stephanschulz** [comment]
thank you very much. it is perfect now. :)
